FROM gradle:jdk21 AS builder

WORKDIR /app

COPY build.gradle .
COPY settings.gradle .
RUN gradle dependencies --no-daemon

COPY src src
RUN gradle build --no-daemon -x test

FROM eclipse-temurin:21-jre-jammy

WORKDIR /app

COPY --from=builder /app/build/libs/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]